{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPVNeeDJrfLl6rPKYbgVOET",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/LuisaPolicarpo/Hotel/blob/main/streamlit_app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "XZNY-pPdq5Oq",
        "outputId": "0b26a1fc-4196-4c8e-e5e4-71d551e54b81"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-04-29 18:06:52.093 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.290 \n",
            "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
            "  command:\n",
            "\n",
            "    streamlit run /usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py [ARGUMENTS]\n",
            "2025-04-29 18:06:52.291 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.294 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.296 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.297 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.298 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.302 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.303 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.304 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.309 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.311 Session state does not function when running a script without `streamlit run`\n",
            "2025-04-29 18:06:52.312 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.313 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.314 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.315 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.317 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.318 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.318 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.320 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.321 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.325 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.326 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.328 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.329 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.330 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.331 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.332 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.336 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.337 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.338 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.339 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.340 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.340 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.341 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.342 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.343 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.343 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.344 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.345 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.346 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.359 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.363 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.364 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-04-29 18:06:52.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        }
      ],
      "source": [
        "import streamlit as st\n",
        "import numpy as np\n",
        "import joblib\n",
        "import requests\n",
        "import io\n",
        "\n",
        "# --- Download the model from GitHub ---\n",
        "url = 'https://raw.githubusercontent.com/LuisaPolicarpo/Hotel/main/cancellation_model.pkl'\n",
        "response = requests.get(url)\n",
        "model = joblib.load(io.BytesIO(response.content))\n",
        "\n",
        "# --- Page Title ---\n",
        "st.title(\"🏨 Hotel Booking Cancellation Predictor\")\n",
        "st.markdown(\"Predict whether a hotel booking will be canceled and take smart actions to reduce risk.\")\n",
        "\n",
        "# --- Sidebar Inputs ---\n",
        "st.sidebar.header(\"📋 Booking Information\")\n",
        "\n",
        "lead_time = st.sidebar.slider(\"Lead Time (days)\", min_value=0, max_value=500, value=100)\n",
        "adr = st.sidebar.number_input(\"Average Daily Rate (ADR)\", min_value=0.0, max_value=500.0, value=100.0)\n",
        "\n",
        "deposit_type = st.sidebar.selectbox(\"Deposit Type\", [\"No Deposit\", \"Non Refund\", \"Refundable\"])\n",
        "customer_type = st.sidebar.selectbox(\"Customer Type\", [\"Transient\", \"Group\", \"Contract\", \"Transient-Party\"])\n",
        "market_segment = st.sidebar.selectbox(\"Market Segment\", [\"Online TA\", \"Direct\", \"Corporate\", \"Offline TA/TO\"])\n",
        "\n",
        "# New features added\n",
        "total_of_special_requests = st.sidebar.slider(\"Total Special Requests\", min_value=0, max_value=5, value=0)\n",
        "booking_changes = st.sidebar.slider(\"Booking Changes\", min_value=0, max_value=10, value=0)\n",
        "previous_cancellations = st.sidebar.slider(\"Previous Cancellations\", min_value=0, max_value=10, value=0)\n",
        "is_repeated_guest = st.sidebar.selectbox(\"Repeated Guest?\", [\"No\", \"Yes\"])\n",
        "is_repeated_guest = 1 if is_repeated_guest == \"Yes\" else 0\n",
        "\n",
        "# --- When the button is clicked ---\n",
        "if st.button(\"Predict Cancellation\"):\n",
        "\n",
        "    # --- Preprocess the Inputs (Manual Encoding) ---\n",
        "\n",
        "    # Deposit Type encoding\n",
        "    deposit_type_no_deposit = 1 if deposit_type == \"No Deposit\" else 0\n",
        "    deposit_type_non_refund = 1 if deposit_type == \"Non Refund\" else 0\n",
        "    # (Refundable = base case)\n",
        "\n",
        "    # Customer Type encoding\n",
        "    customer_type_contract = 1 if customer_type == \"Contract\" else 0\n",
        "    customer_type_group = 1 if customer_type == \"Group\" else 0\n",
        "    customer_type_transient_party = 1 if customer_type == \"Transient-Party\" else 0\n",
        "    # (Transient = base case)\n",
        "\n",
        "    # Market Segment encoding\n",
        "    market_segment_corporate = 1 if market_segment == \"Corporate\" else 0\n",
        "    market_segment_direct = 1 if market_segment == \"Direct\" else 0\n",
        "    market_segment_offline = 1 if market_segment == \"Offline TA/TO\" else 0\n",
        "    # (Online TA = base case)\n",
        "\n",
        "    # --- Create Input Array ---\n",
        "    input_data = np.array([[\n",
        "        lead_time, adr,\n",
        "        deposit_type_no_deposit, deposit_type_non_refund,\n",
        "        customer_type_contract, customer_type_group, customer_type_transient_party,\n",
        "        market_segment_corporate, market_segment_direct, market_segment_offline,\n",
        "        total_of_special_requests,\n",
        "        booking_changes,\n",
        "        previous_cancellations,\n",
        "        is_repeated_guest\n",
        "    ]])\n",
        "\n",
        "    # --- Predict ---\n",
        "    prediction = model.predict(input_data)[0]\n",
        "\n",
        "    # --- Display Result ---\n",
        "    if prediction == 1:\n",
        "        st.error(\"⚠️ This booking is likely to be CANCELED!\")\n",
        "\n",
        "        st.subheader(\"🛠 Suggested Actions to Reduce Cancellation Risk:\")\n",
        "        offer_discount = st.checkbox(\"📧 Send 5% discount email\")\n",
        "        offer_breakfast = st.checkbox(\"🍳 Add free breakfast\")\n",
        "        allow_late_checkout = st.checkbox(\"🕐 Allow late check-in/out\")\n",
        "\n",
        "        if offer_discount or offer_breakfast or allow_late_checkout:\n",
        "            st.success(\"✅ Actions selected! Make sure to notify the guest.\")\n",
        "\n",
        "    else:\n",
        "        st.success(\"✅ This booking is likely to be CONFIRMED!\")"
      ]
    }
  ]
}